### ISSUE TITLE
Installer?

### ISSUE THREAD

**Issue by HDVinnie** [raksit31667/wsp-bkl#38]
Will there be a proper installer for this web application? 

When I follow read me I get following

MacBook-Pro:~ Vinnie$ git clone https://github.com/raksit31667/wsp-bkl.git
Cloning into 'wsp-bkl'...
remote: Counting objects: 829, done.
remote: Total 829 (delta 0), reused 0 (delta 0), pack-reused 829
Receiving objects: 100% (829/829), 606.01 KiB | 1.04 MiB/s, done.
Resolving deltas: 100% (521/521), done.
Checking connectivity... done.
MacBook-Pro:~ Vinnie$ cd wsp-bkl
MacBook-Pro:wsp-bkl Vinnie$ pip install -r requirements.txt
Collecting Django==1.10.1 (from -r requirements.txt (line 1))
  Downloading Django-1.10.1-py2.py3-none-any.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 142kB/s 
Collecting psycopg2==2.6.2 (from -r requirements.txt (line 2))
  Downloading psycopg2-2.6.2.tar.gz (376kB)
    100% |████████████████████████████████| 378kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

```
Error: pg_config executable not found.

Please add the directory containing pg_config to the PATH
or specify the full executable path with the option:

    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.

----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0v/vgcsq9s12pq_vmlnhfrzv7kh0000gn/T/pip-build-1dR6ea/psycopg2/

**Comment by raksit31667** [comment]
I think the problem is you haven't installed pg_config yet, so please try this command:

`sudo apt install libpq-dev python3-dev`

My contributors have got it already so it works fine.

Thanks, and let me know if it works or not
